In [5]:
import numpy as np

my_list = list([4, 5, 6, 7, 89, 9])
my_array = np.array([4, 5, 2, 7, 89, 9])

my_list == my_array # will loop through every valu in array

array([ True,  True, False,  True,  True,  True])

NumPy treats the inner element(s) or list(s) as rows. This is easier to see with a multidimensional array:

```python
np.array([[3,2,0,1],[9,1,8,7],[4,0,1,6]]) # array with 3 rows x 4 columns

>>> array([[3, 2, 0, 1],
           [9, 1, 8, 7],
           [4, 0, 1, 6]])


- if the rows are different lengths, it will not print because we have created an indeterminate position 

In [13]:
a = np.array([[3,2,0,1],
              [9,1,8,7],
              [4,0,4,6]]) # array with 3 rows x 4 columns

# output is nice and formatted
print(a) 

[[3 2 0 1]
 [9 1 8 7]
 [4 0 4 6]]


1. `a`  
    $$
    \begin{bmatrix}
        4 & 5 & 0 & 12 & -1 \\
        8 & -21 & -4 & 6 & 3 \\
        17 & 1 & -13 & 7 & 0
    \end{bmatrix}
    $$

In [16]:
p_1 = np.array([[4, 5, 0, 12, -1],
                       [8, -21, -4, 6, 3],
                       [17, 1, -13, 7, 0]])

print(p_1)

[[  4   5   0  12  -1]
 [  8 -21  -4   6   3]
 [ 17   1 -13   7   0]]


2. `b`  
    $$
    \begin{bmatrix}
        1.0 & 2.7 & 0 & 0.188 & 4.07 & 0.24
    \end{bmatrix}
    $$

In [18]:
p_2 = np.array([1, 2.7, 0, 0.188, 4.7, 0.2])

print(p_2)

[1.    2.7   0.    0.188 4.7   0.2  ]


3. `c`  
    $$
    \begin{bmatrix}
        0.4 \\
        0.8 \\
        1.2 \\
        1.6 \\
        2.0 \\
        2.4
    \end{bmatrix}
    $$

p_3 = np.array([[2], 
                [3],
                [5],
                [5],
                [8],
                [10]])

print(p_3)

# Arrays and Indexing

In [32]:
# Initialize a two-dimensional array
x2 = np.array([[3,2,0,1],
               [9,1,8,7],
               [4,0,1,6]])

# return the value of index = 1 element
## this will output the second row of the array
print(x2[1])


# Return the value of the element in the 2nd row, 3rd column
print(x2[1,3])

[9 1 8 7]
7


In [36]:
# use (axis=1) to calculate averages across columns (# of means is # of rows)
across_column_means = x2.mean(axis=1)
print(across_column_means)

# use (axis=0) to calculate averages down rows (# of means is # of columns)
x2.mean(axis=0)


[1.5  6.25 2.75]


array([5.33333333, 1.        , 3.        , 4.66666667])

# numpy things to remember 

- remember functions 

- remember slicing 

- core functions for interogating (size, shape)

- how to build arrays